openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /posts:
    get:
      summary: Get All
      operationId: get_all_posts_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/WallPost'
                type: array
                title: Response Get All Posts Get
      security:
        - OAuth2PasswordBearer: []
    post:
      summary: Create Post
      operationId: create_post_posts_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WallPost'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WallPost'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  '/posts/{post_id}':
    get:
      summary: Get By Id
      operationId: get_by_id_posts__post_id__get
      security:
        - OAuth2PasswordBearer: []
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
            title: Post Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WallPost'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      summary: Delete
      operationId: delete_posts__post_id__delete
      security:
        - OAuth2PasswordBearer: []
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
            title: Post Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    WallPost:
      properties:
        id:
          anyOf:
            - type: string
            - type: 'null'
          title: Id
        content:
          type: string
          title: Content
        author:
          type: string
          title: Author
        created_at:
          anyOf:
            - type: string
              format: date-time
            - type: 'null'
          title: Created At
      type: object
      required:
        - content
        - author
      title: WallPost
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: login
