version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  user_service:
    build: ./user_service
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_db
    ports:
      - "8000:8000"

  wall_service:
    build: ./wall_service
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_db
    ports:
      - "8001:8001"

volumes:
  db_data:
